version: '3.6'
services:
  redis-single:
    image: redis:6.2.6
    container_name: redis-single6.2.6
    restart: always
    # command: ["redis", "redis-server","/usr/local/etc/redis/redis.conf"]  #使用自定义配置文件启动
    command: ["--requirepass","it9s2cu"]    #默认密码
    volumes:
      - ./conf:/usr/local/etc/redis
      - ./data:/data
    ports:
      - 6379:6379
