version: '3.1'

services:

  postgres:
    build: ./
    container_name: postgres14.1
    # restart: always
    environment:
      POSTGRES_PASSWORD: it9s2cu
    volumes:
      - ./data:/var/lib/postgresql/data 
      - ./conf:/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432