version: '3.6'
services:
  vue2.6.11:
    build: ../
    container_name: vue2.6.11_nginx1.21.5
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80