version: '3.6'
services:
  web:
    build: ../
    container_name: react17.0.2_nginx1.21.5
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80