version: '3.6'
services:
  web:
    image: nginx:1.21.5
    volumes:
    - ../build:/usr/share/nginx/html
    # - $PWD/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "8080:80"
    environment:
    - NGINX_PORT=80