version: '3.7'
services:
  minio-single:
    image: quay.io/minio/minio
    container_name: minio-single 
    command: ["server", "/data","--console-address",":9001"]
    environment:
      - MINIO_ROOT_USER=admin         
      - MINIO_ROOT_PASSWORD=admin123
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
      - 9001:9001

    

