version: '3.7'
services:
  minio-erasurecode:
    image: quay.io/minio/minio
    container_name: minio-erasure-code
    command: ["server", "/data{1...8}","--console-address",":9001"]
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    volumes:
      - ./data1:/data1
      - ./data2:/data2
      - ./data3:/data3
      - ./data4:/data4
      - ./data5:/data5
      - ./data6:/data6
      - ./data7:/data7
      - ./data8:/data8
    ports:
      - 9000:9000
      - 9001:9001