version: '3.6'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.5
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - 2181:2181
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M

  kafka:
    image: confluentinc/cp-kafka:5.5.5
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092 # Uncomment to make Kafka available externally
    links:
      - zookeeper
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8192M

  kafka-manager:
    image: sheepkiller/kafka-manager
    links:
      - zookeeper
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M