version: '3.6'
services:
  portainer:
    image: 'portainer/portainer-ce:2.11.0-alpine'
    ports:
      - 9000:9000
      - 9443:9443
    container_name: portainer
    # restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '$PWD/data:/data'
