version: "3.6"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - '2181'
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M

  zookeeper2:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - '2181'
    volumes:
      - zookeeper2_data:/bitnami
    environment:
      - ZOO_SERVER_ID=2
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M

  zookeeper3:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - '2181'
    volumes:
      - zookeeper3_data:/bitnami
    environment:
      - ZOO_SERVER_ID=3
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M

  kafka-0:
    image: docker.io/bitnami/kafka:3.1
    ports:
      - "9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181,zookeeper2:2181,zookeeper3:2181
      - KAFKA_CFG_BROKER_ID=0
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_0_data:/bitnami/kafka
    depends_on:
      - zookeeper
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8192M

  kafka-1:
    image: docker.io/bitnami/kafka:3.1
    ports:
      - "9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181,zookeeper2:2181,zookeeper3:2181
      - KAFKA_CFG_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_1_data:/bitnami/kafka
    depends_on:
      - zookeeper
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8192M

  kafka-2:
    image: docker.io/bitnami/kafka:3.1
    ports:
      - "9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181,zookeeper2:2181,zookeeper3:2181
      - KAFKA_CFG_BROKER_ID=2
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_2_data:/bitnami/kafka
    depends_on:
      - zookeeper
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8192M

  kafka-manager:
    image: sheepkiller/kafka-manager
    environment:
      ZK_HOSTS: zookeeper:2181,zookeeper2:2181,zookeeper3:2181
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M


volumes:
  kafka_0_data:
    driver: local
  kafka_1_data:
    driver: local
  kafka_2_data:
    driver: local
  zookeeper_data:
    driver: local
  zookeeper2_data:
    driver: local
  zookeeper3_data:
    driver: local