{
 "title": "MYSQL",
 "description": "阿里云数据库(MySql)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS", "label": "DataSource", "query": "prometheus" },
   {
    "name": "Database",
    "query": {
     "query": "label_values(mysql_up,Category)"
    }
   },
   {
    "name": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "SQL执行计数",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "round(irate(mysql_global_status_commands_total{command=~\"load|lock_tables|show_slave_lag|show_slave_status\",Category=\"$Database\"}[1m]))",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "innodb_rows_operation",
   "type": "table-old",
   "description": "Innodb_rows_deleted\n从innodb表中删除的行数。单位是行\n\nInnodb_rows_inserted\n插入到innodb表中的行数。单位是行\n\nInnodb_rows_updated\ninnodb表中更新的行数。单位是行\n\nInnodb_rows_read\n从innodb表中读取的行数。单位是行",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "mysql_global_status_innodb_row_ops_total{Category=\"$Database\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "handler action",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "irate(mysql_global_status_handlers_total{Category=\"$Database\"}[1m])"
    }
   ]
  },
  { "title": "DB Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "活动连接",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "round(irate(mysql_global_status_connections{Category=\"$Database\"}[10s]))",
     "legendFormat": "连接"
    }
   ]
  },
  {
   "title": "innodb write/read 速率",
   "type": "graph",
   "description": "Innodb_data_read   表示Innodb启动后，从物理磁盘上读取的字节数总和\nInnodb_data_wirtten   表示Innodb启动后，从物理磁盘上写入的字节数总和\n\nInnodb_data_reads 表示Innodb启动后，对物理磁盘发起的IO请求次数总和\nInnodb_data_writes 表示Innodb启动后，对物理磁盘发起的IO写入次数总和\n\nInnodb_data_read / Innodb_data_reads 得到的比值，越接近16K说明IO压力越倾向于随机IO，越远离16K说明IO从顺序预读中获得性能提升越多",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "round(irate(mysql_global_status_innodb_data_written{Category=\"$Database\"}[10s]))",
     "legendFormat": "write"
    },
    {
     "expr": "round(irate(mysql_global_status_innodb_data_read{Category=\"$Database\"}[10s]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "innodb_log_waits",
   "type": "graph",
   "description": "因日志缓存太小而必须等待其被写入所造成的等待数。单位是次",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_innodb_log_waits{Category=\"$Database\"}",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "innodb_log_write_requests",
   "type": "graph",
   "description": "innodb日志写入请求数，单位（次）",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "round(irate(mysql_global_status_innodb_log_write_requests{Category=\"$Database\"}[1m]))",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "innodb_log_writes",
   "type": "graph",
   "description": "innodb log buffer写入log file的总次数。单位（次）",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "round(irate(mysql_global_status_innodb_log_writes{Category=\"$Database\"}[10s]))",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "innodb_row_lock_current_waits",
   "type": "graph",
   "description": "innodb当前正在等待行锁的数量。单位是个\n",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "round(irate(mysql_global_status_innodb_row_lock_current_waits{Category=\"$Database\"}[10s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "innodb_row_lock_time_avg",
   "type": "graph",
   "description": "innodb获取行锁等待的平均时间。单位是毫秒\n\n",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_innodb_row_lock_time_avg{Category=\"$Database\"}",
     "legendFormat": "毫秒"
    }
   ]
  },
  {
   "title": "innodb_row_lock_waits",
   "type": "graph",
   "description": "\n\ninnodb等待获取行锁的次数。单位是次",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "idelta(mysql_global_status_innodb_row_lock_waits{Category=\"$Database\"}[10s])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "key_read/write",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_key_reads{Category=\"$Database\"}",
     "legendFormat": "read"
    },
    {
     "expr": "mysql_global_status_key_writes{Category=\"$Database\"}",
     "legendFormat": "wirte"
    }
   ]
  },
  {
   "title": "max_used_connections",
   "type": "graph",
   "description": "数据库响应过的最大并发连接数\n\nMax_used_connections / max_connections * 100% ≈ 85%\n最大连接数占上限连接数的85%左右，如果发现比例在10%以下，MySQL服务器连接数上限设置的过高了",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{Category=\"$Database\"}"
    }
   ]
  },
  {
   "title": "qcache_free_memory",
   "type": "graph",
   "description": "查询缓存的内存大小",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_qcache_free_memory{Category=\"$Database\"}",
     "legendFormat": "AvailableCache"
    }
   ]
  },
  {
   "title": "select_scan",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_select_scan{Category=\"$Database\"}[1m])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "table_locks_waited",
   "type": "graph",
   "description": "Table_locks_immediate 表示立即释放表锁数，Table_locks_waited表示需要等待的表锁数，如果 Table_locks_immediate / Table_locks_waited > 5000，最好采用InnoDB引擎，因为InnoDB是行锁而MyISAM是表锁，对于高并发写入的应用InnoDB效果会好些",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_table_locks_waited{Category=\"$Database\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "binlog_cache_size",
   "type": "graph",
   "description": "Binlog_cache_disk_use表示因为我们binlog_cache_size设计的内存不足导致缓存二进制日志用到了临时文件的次数\n\nBinlog_cache_use  表示 用binlog_cache_size缓存的次数\n\n当对应的Binlog_cache_disk_use 值比较大的时候 我们可以考虑适当的调高 binlog_cache_size 对应的值\n",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mysql_global_variables_binlog_cache_size{Category=\"$Database\"}",
     "legendFormat": "Cache size"
    }
   ]
  },
  {
   "title": "innodb_deadlock_detect",
   "type": "graph",
   "description": "作用：该选项使用了禁用MySQL的死锁检测功能的。在高并发系统上，当许多线程等待同一个锁时，死锁检测可能导致速度减慢。 有时，当发生死锁时，如果禁用了死锁检测则可能会更有效，这样可以依赖innodb_lock_wait_timeout的设置进行事务回滚\n\n默认值：ON",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mysql_global_variables_innodb_deadlock_detect{Category=\"$Database\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "innodb_lock_wait_timeout",
   "type": "graph",
   "description": "Mysql数据库采用InnoDB模式，默认参数:innodb_lock_wait_timeout设置锁等待的时间是50s，一旦数据库锁超过这个时间就会报错\n\n简而言之，就是事务锁超时时间",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mysql_global_variables_innodb_lock_wait_timeout{Category=\"$Database\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "max_tmp_tables",
   "type": "graph",
   "description": "最大临时表个数\n\n每次创建临时表，Created_tmp_tables增加，如果临时表大小超过tmp_table_size，则是在磁盘上创建临时表，Created_tmp_disk_tables也增加,Created_tmp_files表示MySQL服务器创建的临时文件文件数，比较理想的配置是：\n\nCreated_tmp_disk_tables / Created_tmp_tables * 100% <= 25%比如上面的服务器Created_tmp_disk_tables / Created_tmp_tables * 100% ＝1.20%，应该相当好了",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mysql_global_variables_max_tmp_tables{Category=\"$Database\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "lock_row_lock_current_waits_total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mysql_info_schema_innodb_metrics_lock_lock_row_lock_current_waits_total{Category=\"$Database\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "no_good_index_used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mysql_perf_schema_events_statements_sum_no_good_index_used{Category=\"$Database\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "slow_queries",
   "type": "graph",
   "description": "当前慢查询",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "idelta(mysql_global_status_slow_queries{Category=\"$Database\"}[10s])",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "rows_examined_total ",
   "type": "table-old",
   "description": "检索的行数，执行SQL时",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "topk(10,irate(mysql_perf_schema_events_statements_rows_examined_total {Category=\"$Database\"}[1m]))",
     "legendFormat": "{{digest}}: {{digest_text}}"
    }
   ]
  },
  {
   "title": "no_index_used_total",
   "type": "table-old",
   "description": "未使用索引SQL语句",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "topk(10,idelta(mysql_perf_schema_events_statements_no_index_used_total{Category=\"$Database\"}[10s]))",
     "legendFormat": "{{digest}}: {{digest_text}}"
    }
   ]
  }
 ]
}